services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: passwordbdd
      MYSQL_DATABASE: zoo_bdd
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 8080:80
    
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
      - ./app:/var/www
    depends_on:
      - database
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: passwordbdd
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb:/data/db    